### ISSUE TITLE
FlipCard throws exception if container not constrained

### ISSUE THREAD

**Issue by bsutton** [BrunoJurkovic/flip_card#13]
I have a very simple flip card that is throwing an exception:

I'm expecting the flip card to size itself to the content.

The real content I'm looking to use is an expanding card and as such the size of the flip card needs change with the expanding card does.
```


class ContactCard extends StatelessWidget

  @override
  Widget build(BuildContext context) {
    return Container(child: FlipCard(direction: FlipDirection.HORIZONTAL,
        front: buildFront(),
        back: buildBack()
      ),
        );
  }

  Widget buildBack()
  {
    return Container( child:Text("Back"), height: 100);
  }

  Widget buildFront()
  {
    return Container( child:Text("Front"), height: 100);
  }

}
```

The card is throwing the following exception:

```
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 4871): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4871): The following assertion was thrown during performLayout():
I/flutter ( 4871): BoxConstraints forces an infinite height.
I/flutter ( 4871): These invalid constraints were provided to RenderIgnorePointer's layout() function by the following
I/flutter ( 4871): function, which probably computed the invalid constraints in question:
I/flutter ( 4871):   RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4871): The offending constraints were:
I/flutter ( 4871):   BoxConstraints(w=411.4, h=Infinity)
I/flutter ( 4871): 
I/flutter ( 4871): When the exception was thrown, this was the stack:
I/flutter ( 4871): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:507:9)
I/flutter ( 4871): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:550:21)
I/flutter ( 4871): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:554:6)
I/flutter ( 4871): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1536:24)
I/flutter ( 4871): #4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4871): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4871): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #22     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter ( 4871): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #24     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 4871): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #26     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 4871): #27     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 4871): #28     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 4871): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #48     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
I/flutter ( 4871): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #50     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 4871): #51     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 4871): #52     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 4871): #53     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 4871): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #58     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 4871): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #75     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3076:13)
I/flutter ( 4871): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #77     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4871): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #79     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4871): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 4871): #91     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter ( 4871): #92     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 4871): #93     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 4871): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 4871): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4871): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 4871): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 4871): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 4871): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter ( 4871): #101    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 4871): #102    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 4871): #103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 4871): (elided one frame from package dart:async-patch)
I/flutter ( 4871): 
I/flutter ( 4871): The following RenderObject was being processed when the exception was fired: RenderStack#2e82f relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 4871):   creator: Stack ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← FlipCard ←
I/flutter ( 4871):     Container ← ContactCard ← FractionalTranslation ← SlideTransition ← Stack ← Listener ← ⋯
I/flutter ( 4871):   parentData: <none> (can use size)
Reloaded 3 of 619 libraries in 259ms.
I/flutter ( 4871):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
I/flutter ( 4871):   size: MISSING
I/flutter ( 4871):   alignment: AlignmentDirectional.topStart
I/flutter ( 4871):   textDirection: ltr
I/flutter ( 4871):   fit: expand
I/flutter ( 4871):   overflow: clip
I/flutter ( 4871): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4871):     child 1: RenderIgnorePointer#6912a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):       child: RenderTransform#daf87 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):         child: RenderConstrainedBox#e7f9f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):           child: RenderParagraph#0936e NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4871):             text: TextSpan
I/flutter ( 4871):     child 2: RenderIgnorePointer#d2321 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):       child: RenderTransform#b0f27 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):         child: RenderConstrainedBox#fe06f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):           child: RenderParagraph#fb2b6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871):             text: TextSpan
I/flutter ( 4871): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderStack#2e82f relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#9f8a0 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#3fa65 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871): Another exception was thrown: BoxConstraints forces an infinite height.
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderStack#34d05 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#77e43 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 4871): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#62268 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

```

**Comment by feibyte** [comment]
Thanks for your feedback. I think we should address this issue.
But could you shed more light on your expectation?
What do you mean of `size itself to the content`? What if the two sides have a different size?

**Comment by bsutton** [comment]
I am using an ExpansionTile (https://flutter.dev/docs/catalog/samples/expansion-tile-sample) .
The ExpandingTile contains a heading and a body.
The body is initially hidden.
When you click the heading of the ExpandingTile it increases its height to show the body.

I'm then using a FlipCard to wrap the Expansion Tile.

e.g. 
```
FlipCard( front: ExpandingTile(
                              title: Text("heading"), 
                              body: Text("body"))
                back: Text("back of card")
);
```
When the Expanding tile expands I need the FlipCard to also increase in size.
The body of my ExpandingTile contains an Icon.
When the user clicks the icon I activate the FlipCard to flip the ExpandingCard.

Hopefully that make sense.

**Comment by feibyte** [comment]
Yeah, Fair enough. 
I've checked my code.  Currently, I'm using `fit: StackFit.expand`, I think you're right and it'd better be `fit: StackFit.passthrough`. That means I'll leave it to you to take care of it.

I've published a new version. Hope it's what you expect.

**Comment by bsutton** [comment]
Thanks.
I will give it a try.

**Comment by feibyte** [comment]
@bsutton  Can I close this issue now?

**Comment by bsutton** [comment]
I've still not had a chance to check it out, but go ahead and close it as I can always re-open if there is a problem.
